architecture-beta
    group api(cloud)[API]
    service db(database)[Database] in api
    service disk1(disk)[Storage] in api
    service server(server)[Server] in api
    service gw(internet)[Gateway]
    junction j1
    db:L -- R:server
    disk1:T -- B:server
    gw:R --> L:j1
    j1:R --> L:server
