gantt
    title Launch
    dateFormat YYYY-MM-DD
    excludes weekends
    section Design
    Research             :done, des1, 2026-09-01, 5d
    Prototype            :active, des2, after des1, 7d
    section Development
    Backend              :crit, dev1, after des2, 10d
    Frontend             :dev2, after des2, 8d
    Integration          :dev3, after dev1 dev2, 3d
    section Release
    Beta                 :milestone, m1, after dev3, 0d
    Announcement         :4d
