timeline
    title Historia de las redes sociales
    section Primeros años
      2002 : LinkedIn
      2004 : Facebook : Google
    section Expansión
      2005 : YouTube
      2006 : Twitter
           : Spotify
